### ISSUE TITLE
Is there any way to add/remove classes `atEnter`, `atLeave`, and `atActive`? 

### ISSUE THREAD

**Issue by Lathryx** [maisano/react-router-transition#124]
I'm attempting to add/remove a `.hide` class: 
```css
.hide {
    margin: 0; 
    padding: 0; 
    width: 0; 
    height: 0; 
    opacity: 0; 
}
``` 
Which essentially allows other elements to pass over the corresponding element in its `atLeave` state, of course given that element has this class. Then, on this element's `atEnter` stage, I must promptly remove this class. 

_Is there any known way of doing this?_
